-- MySQL Script generated by MySQL Workbench
-- Thu Oct 28 15:39:44 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema nakamax
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `nakamax` ;

-- -----------------------------------------------------
-- Schema nakamax
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nakamax` DEFAULT CHARACTER SET utf8 ;
USE `nakamax` ;

-- -----------------------------------------------------
-- Table `nakamax`.`campradores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nakamax`.`campradores` ;

CREATE TABLE IF NOT EXISTS `nakamax`.`campradores` (
  `id_comprador` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `apellidos` VARCHAR(255) NOT NULL,
  `usuario_tag` VARCHAR(255) NOT NULL,
  `genero_favorito` VARCHAR(255) NOT NULL,
  `correo` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  PRIMARY KEY (`id_comprador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nakamax`.`vendedores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nakamax`.`vendedores` ;

CREATE TABLE IF NOT EXISTS `nakamax`.`vendedores` (
  `id_vendedor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `apellidos` VARCHAR(255) NOT NULL,
  `rfc` VARCHAR(255) NOT NULL,
  `correo` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `telefono` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_vendedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nakamax`.`personalizables`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nakamax`.`personalizables` ;

CREATE TABLE IF NOT EXISTS `nakamax`.`personalizables` (
  `id_personalizable` INT NOT NULL AUTO_INCREMENT,
  `size` VARCHAR(255) NOT NULL,
  `color` VARCHAR(255) NOT NULL,
  `material` VARCHAR(255) NOT NULL,
  `costo_extra` FLOAT NOT NULL,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`id_personalizable`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nakamax`.`productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nakamax`.`productos` ;

CREATE TABLE IF NOT EXISTS `nakamax`.`productos` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `costo` FLOAT NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  `imagen` VARCHAR(255) NOT NULL,
  `stock` INT NULL,
  `personalizable` TINYINT(1) NULL,
  `id_vendedor` INT NOT NULL,
  `id_personalizable` INT NULL,
  PRIMARY KEY (`id_producto`),
  INDEX `fk_productos_vendedores_idx` (`id_vendedor` ASC) INVISIBLE,
  INDEX `fk_productos_personalizables_idx` (`id_personalizable` ASC) VISIBLE,
  CONSTRAINT `fk_productos_vendedores`
    FOREIGN KEY (`id_vendedor`)
    REFERENCES `nakamax`.`vendedores` (`id_vendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productos_personalizables`
    FOREIGN KEY (`id_personalizable`)
    REFERENCES `nakamax`.`personalizables` (`id_personalizable`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nakamax`.`categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nakamax`.`categorias` ;

CREATE TABLE IF NOT EXISTS `nakamax`.`categorias` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `descrpcion` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nakamax`.`compra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nakamax`.`compra` ;

CREATE TABLE IF NOT EXISTS `nakamax`.`compra` (
  `id_compra` INT NOT NULL AUTO_INCREMENT,
  `fecha_compra` TIMESTAMP NOT NULL,
  `id_comprador` INT NOT NULL,
  PRIMARY KEY (`id_compra`),
  INDEX `fk_compra_campradores_idx` (`id_comprador` ASC) VISIBLE,
  CONSTRAINT `fk_compra_campradores`
    FOREIGN KEY (`id_comprador`)
    REFERENCES `nakamax`.`campradores` (`id_comprador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nakamax`.`reportes_producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nakamax`.`reportes_producto` ;

CREATE TABLE reportes_producto (
  id_reporte INT NOT NULL AUTO_INCREMENT,
  descripcion VARCHAR(255) NOT NULL,
  is_llego TINYINT(1) NULL,
  is_danger TINYINT(1) NULL,
  is_tardio TINYINT(1) NULL,
  id_compra INT NOT NULL,
  PRIMARY KEY (id_reporte),
  INDEX fk_reportes_producto_compra_idx (id_compra ASC) VISIBLE,
  CONSTRAINT fk_reportes_producto_compra
    FOREIGN KEY (id_compra)
    REFERENCES nakamax.compra (id_compra)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nakamax`.`reportes_pagina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nakamax`.`reportes_pagina` ;

CREATE TABLE IF NOT EXISTS `nakamax`.`reportes_pagina` (
  `id_reporte_pag` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NOT NULL,
  `is_general` TINYINT(1) NULL,
  `is_link_down` VARCHAR(45) NULL,
  PRIMARY KEY (`id_reporte_pag`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nakamax`.`cometarios_contac_us`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nakamax`.`cometarios_contac_us` ;

CREATE TABLE IF NOT EXISTS `nakamax`.`cometarios_contac_us` (
  `id_comentario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL,
  `correo` VARCHAR(255) NOT NULL,
  `telefono` VARCHAR(255) NULL,
  `comentario` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_comentario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nakamax`.`administradores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nakamax`.`administradores` ;

CREATE TABLE IF NOT EXISTS `nakamax`.`administradores` (
  `id_admin` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `apellido_paterno` VARCHAR(255) NOT NULL,
  `apellido_materno` VARCHAR(255) NOT NULL,
  `correo` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `imagen` VARCHAR(255) NOT NULL,
  `github` VARCHAR(255) NOT NULL,
  `linkedin` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_admin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nakamax`.`pivote_prod_cat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nakamax`.`pivote_prod_cat` ;

CREATE TABLE IF NOT EXISTS `nakamax`.`pivote_prod_cat` (
  `id_producto` INT NOT NULL,
  `id_categoria` INT NOT NULL,
  INDEX `fk_pivote_prod_cat_productos_idx` (`id_producto` ASC) VISIBLE,
  INDEX `fk_pivote_prod_cat_categorias_idx` (`id_categoria` ASC) VISIBLE,
  CONSTRAINT `fk_pivote_prod_cat_productos`
    FOREIGN KEY (`id_producto`)
    REFERENCES `nakamax`.`productos` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pivote_prod_cat_categorias`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `nakamax`.`categorias` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nakamax`.`pivote_comp_prod`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nakamax`.`pivote_comp_prod` ;

CREATE TABLE IF NOT EXISTS `nakamax`.`pivote_comp_prod` (
  `id_compra` INT NOT NULL,
  `id_producto` INT NOT NULL,
  INDEX `fk_pivote_comp_prod_compra_idx` (`id_compra` ASC) VISIBLE,
  INDEX `fk_pivote_comp_prod_productos_idx` (`id_producto` ASC) VISIBLE,
  CONSTRAINT `fk_pivote_comp_prod_compra`
    FOREIGN KEY (`id_compra`)
    REFERENCES `nakamax`.`compra` (`id_compra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pivote_comp_prod_productos`
    FOREIGN KEY (`id_producto`)
    REFERENCES `nakamax`.`productos` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nakamax`.`piv_repo_comp`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nakamax`.`piv_repo_comp` ;

CREATE TABLE IF NOT EXISTS `nakamax`.`piv_repo_comp` (
  `id_comprador` INT NOT NULL,
  `id_reporte_pag` INT NOT NULL,
  INDEX `fk_piv_repo_comp_campradores_idx` (`id_comprador` ASC) VISIBLE,
  INDEX `fk_piv_repo_comp_reportes_pagina_idx` (`id_reporte_pag` ASC) VISIBLE,
  CONSTRAINT `fk_piv_repo_comp_campradores`
    FOREIGN KEY (`id_comprador`)
    REFERENCES `nakamax`.`campradores` (`id_comprador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_piv_repo_comp_reportes_pagina`
    FOREIGN KEY (`id_reporte_pag`)
    REFERENCES `nakamax`.`reportes_pagina` (`id_reporte_pag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nakamax`.`piv_adm_repo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nakamax`.`piv_adm_repo` ;

CREATE TABLE IF NOT EXISTS `nakamax`.`piv_adm_repo` (
  `id_admin` INT NOT NULL,
  `id_reporte_pag` INT NOT NULL,
  INDEX `fk_piv_adm_repo_administradores_idx` (`id_admin` ASC) VISIBLE,
  INDEX `fk_piv_adm_repo_reportes_pagina_idx` (`id_reporte_pag` ASC) VISIBLE,
  CONSTRAINT `fk_piv_adm_repo_administradores`
    FOREIGN KEY (`id_admin`)
    REFERENCES `nakamax`.`administradores` (`id_admin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_piv_adm_repo_reportes_pagina`
    FOREIGN KEY (`id_reporte_pag`)
    REFERENCES `nakamax`.`reportes_pagina` (`id_reporte_pag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nakamax`.`piv_repo_vend`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nakamax`.`piv_repo_vend` ;

CREATE TABLE IF NOT EXISTS `nakamax`.`piv_repo_vend` (
  `id_reporte_pag` INT NOT NULL,
  `id_vendedor` INT NOT NULL,
  INDEX `fk_piv_repo_vend_reportes_pagina_idx` (`id_reporte_pag` ASC) VISIBLE,
  INDEX `fk_piv_repo_vend_vendedores_idx` (`id_vendedor` ASC) VISIBLE,
  CONSTRAINT `fk_piv_repo_vend_reportes_pagina`
    FOREIGN KEY (`id_reporte_pag`)
    REFERENCES `nakamax`.`reportes_pagina` (`id_reporte_pag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_piv_repo_vend_vendedores`
    FOREIGN KEY (`id_vendedor`)
    REFERENCES `nakamax`.`vendedores` (`id_vendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nakamax`.`piv_conus_admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nakamax`.`piv_conus_admin` ;

CREATE TABLE IF NOT EXISTS `nakamax`.`piv_conus_admin` (
  `id_comentario` INT NOT NULL,
  `id_admin` INT NOT NULL,
  INDEX `fk_piv_conus_admin_cometarios_contac_us_idx` (`id_comentario` ASC) VISIBLE,
  INDEX `fk_piv_conus_admin_administradores_idx` (`id_admin` ASC) VISIBLE,
  CONSTRAINT `fk_piv_conus_admin_cometarios_contac_us`
    FOREIGN KEY (`id_comentario`)
    REFERENCES `nakamax`.`cometarios_contac_us` (`id_comentario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_piv_conus_admin_administradores`
    FOREIGN KEY (`id_admin`)
    REFERENCES `nakamax`.`administradores` (`id_admin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nakamax`.`piv_adm_repro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nakamax`.`piv_adm_repro` ;

CREATE TABLE IF NOT EXISTS `nakamax`.`piv_adm_repro` (
  `id_admin` INT NOT NULL,
  `id_reporte` INT NOT NULL,
  INDEX `fk_piv_adm_repro_administradores_idx` (`id_admin` ASC) VISIBLE,
  INDEX `fk_piv_adm_repro_reportes_producto_idx` (`id_reporte` ASC) VISIBLE,
  CONSTRAINT `fk_piv_adm_repro_administradores`
    FOREIGN KEY (`id_admin`)
    REFERENCES `nakamax`.`administradores` (`id_admin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_piv_adm_repro_reportes_producto`
    FOREIGN KEY (`id_reporte`)
    REFERENCES `nakamax`.`reportes_producto` (`id_reporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nakamax`.`piv_vend_repro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nakamax`.`piv_vend_repro` ;

CREATE TABLE IF NOT EXISTS `nakamax`.`piv_vend_repro` (
  `id_reporte` INT NOT NULL,
  `id_vendedor` INT NOT NULL,
  INDEX `fk_piv_vend_repro_reportes_producto_idx` (`id_reporte` ASC) VISIBLE,
  INDEX `fk_piv_vend_repro_vendedores_idx` (`id_vendedor` ASC) VISIBLE,
  CONSTRAINT `fk_piv_vend_repro_reportes_producto`
    FOREIGN KEY (`id_reporte`)
    REFERENCES `nakamax`.`reportes_producto` (`id_reporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_piv_vend_repro_vendedores`
    FOREIGN KEY (`id_vendedor`)
    REFERENCES `nakamax`.`vendedores` (`id_vendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


